from .user import *
from .admin import *
from .staff import *
from .courseStaff import *
from .course import *
from .assessment import *
from .courseAssessment import *
from .courseProgramme import *
from .programme import *
from .schedule import *